security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_RE, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                login_path: /login
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /admin
                use_referer: true
                always_use_default_target_path: false
                target_path_parameter: _target_path
                failure_path: /login
            logout:
                path: /logout
                target: /login
                invalidate_session: false
            anonymous: true
            remember_me:
                key: "%secret%"
                lifetime: 3600
                path: /login
                domain: local.checkeate.com
                user_provider: fos_userbundle

    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile/, role: ROLE_USER }
        - { path: ^/logout/, role: ROLE_USER }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^(/admin), role: ROLE_ADMIN }