# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.profile.form.type:
        class: AppBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: app_profile }
    sliderService:
        class: AppBundle\Controller\Admin\SliderController
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
